#!/bin/bash

ARCH=`uname`.`uname -m`
case $0 in
 ./*) export PHYLOCSF_BASE=`pwd` ;;
  * ) export PHYLOCSF_BASE=`dirname $0`
esac

if [ -f "$PHYLOCSF_BASE/cde-package.$ARCH.tar" ]; then
  if [ ! -d "$PHYLOCSF_BASE/cde-package.$ARCH" ]; then
    tar x -C $PHYLOCSF_BASE -f $PHYLOCSF_BASE/cde-package.$ARCH.tar
  fi
  $PHYLOCSF_BASE/cde-package.$ARCH/cde-exec /home/mlin/src/PhyloCSF/PhyloCSF.$ARCH $@
else
  echo "No executable available for architecture: $ARCH"
fi
